fixes for crd client
3scale-qe/3scale-api-python pull request #128
Opened 2022-08-11 08:02 UTC by mkudlej

Fixes needed for crd client

2022-08-11 10:16 UTC, mdujava submitted a review, later dismissed

2022-08-22 07:30 UTC, mganisin requested changes

2022-08-22 07:30 UTC, mganisin commented on .gitignore
> +Pipfile.lock
Don't add Pipfile.lock to .gitignore

2022-08-29 12:36 UTC, mdujava approved these changes

2022-08-31 20:28 UTC, mganisin approved these changes

2022-08-31 20:28 UTC, merged