Add invoice payment transactions endpoint
3scale-qe/3scale-api-python pull request #129
Opened 2022-09-19 15:28 UTC by averevki

2022-09-20 08:52 UTC, JaurbanRH submitted a review, later dismissed

2022-09-26 11:23 UTC, jsmolar requested changes
Please add tests.

2022-09-27 07:42 UTC, jsmolar commented on tests/integration/conftest.py
> +def stripe_init(stripe_api_key):
use autouse :) https://docs.pytest.org/en/6.2.x/fixture.html

2022-09-27 11:33 UTC, averevki commented
@mganisin can you please review this PR, specifically if stripe api is ok to add to dev-packages

2022-09-29 09:08 UTC, mganisin commented
I am not sold to the idea that such integration test should be here.
 - this represents another external dependency - doesn't have to be clear how to fullfil it
 - without proper setup this will fail always, if ran as of now, the result would be red (kind of a regression, but not a regression actually)

I am still undecided

2022-09-30 04:39 UTC, mganisin commented
@averevki split it into two requests please, keep tests in separate PR, that will allow us to merge the feature and give bit more time to think about the tests

2022-10-02 07:50 UTC, jsmolar approved these changes

2022-10-03 11:02 UTC, merged