Fix asserts
3scale-qe/3scale-api-python pull request #163
Opened 2024-12-13 15:04 UTC by mkudlej

2024-12-16 10:04 UTC, mdujava requested changes

2024-12-16 12:05 UTC, mdujava submitted a review, later dismissed

2025-01-07 12:15 UTC, mdujava requested changes

2025-01-07 12:15 UTC, mdujava commented on tests/integration/asserts.py
> +            assert obj[key] == val, f"Resource hasn't expected value for a \"{key}\". {obj[key]} == {val}"
`doesn't have expected ...`  or `hasn't got expected ...`

2025-01-07 12:36 UTC, mdujava approved these changes

2025-01-07 12:47 UTC, mastastny approved these changes

2025-01-07 13:05 UTC, merged